runtime: python39

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

# Optional: entrypoint to run your application
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FLASK_ENV: 'production'

# Use the smallest instance class (F1) which is free tier eligible
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 1  # Limit to 1 instance to avoid charges

# Optional: reduce max_idle_instances to save costs
basic_scaling:
  max_instances: 1
  idle_timeout: 5m
